### ISSUE TITLE
Terrablender has failed to load correctly java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by PyroProtogen** [Glitchfiend/TerraBlender#100]
### What's the issue you encountered?

whenever i try to load minecraft with this mod it comes up with the error Terrablender has failed to load correctly java.lang.ExceptionInInitializerError: null

### How can the issue be reproduced?

Unknown

### Logs

https://gist.github.com/PyroProtogen/d9559d24e6a1445bd50b518e39564f49#file-gistfile1-txt

### Mod Version

2.0.1.128

**Comment by Adubbz** [comment]
You need to delete your config files.
