### ISSUE TITLE
Crash at client start

### ISSUE THREAD

**Issue by TheButterbrotMan** [Glitchfiend/TerraBlender#102]
### What's the issue you encountered?

My client is crashing on launching.

### How can the issue be reproduced?

Im not sure tbh. The game worked. After a restarted it stopped working.

### Logs

https://bytebin.lucko.me/QR2hA8cX9S

### Mod Version

2.1.0.132

**Comment by TheButterbrotMan** [comment]
https://github.com/Cristelknight999/WWOO/issues/16

**Comment by Adubbz** [comment]
As noted on the other issue you opened, this isn’t actually a TerraBlender issue
