### ISSUE TITLE
521 error

### ISSUE THREAD

**Issue by MJRamon** [Glitchfiend/TerraBlender#103]
### What's the issue you encountered?

I've updated dependencies, and now I'm getting
Could not HEAD 'https://jitpack.io/com/github/glitchfiend/TerraBlender-fabric/1.19.2-2.0.1.136/TerraBlender-fabric-1.19.2-2.0.1.136.pom'. Received status code 521 from server

This is going on for several hours. Jitpack status says servers are operational.
Offline mode is not enabled in IntelliJ. Is Jitpack broken or something broke on my end?

### How can the issue be reproduced?

Run IntelliJ

### Mod Version

1.19.2-2.0.1.136

**Comment by Adubbz** [comment]
You probably don’t have the Forge maven set up in gradle correctly, which is required even for the Fabric version. I have no idea what jitpack is, we don’t use it

**Comment by MJRamon** [comment]
Yeah, I've placed `maven { url 'https://jitpack.io' }` last in repositories list and now it works.
Jitpack, as it shows, is a pile of garbage.
