### ISSUE TITLE
Cave biomes generate above ground in 1.19.2

### ISSUE THREAD

**Issue by vaylor27** [Glitchfiend/TerraBlender#108]
### What's the issue you encountered?

Cave biomes generate above ground in 1.19.2 with all of the features on the surface and biome shows in debug screen on the surface.

### How can the issue be reproduced?

Code an underground biome.

### Mod Version

All of them.

**Comment by Adubbz** [comment]
This is not an issue with TerraBlender. It’s an issue with whatever mods you have that adds a region and doesn’t have their parameters set up correctly.

**Comment by vaylor27** [comment]
Then how do I set up parameters correctly? I copied biomes O' plenty code and it still doesn't work!

**Comment by Adubbz** [comment]
You shouldn't be copying BOP's code, both because it's not for general purposes and because the license doesn't permit it. If you don't know how to use TerraBlender you should look at the examples.

**Comment by vaylor27** [comment]
I am just using it for testing. (No BOP code in the final mod)

**Comment by vaylor27** [comment]
and how do I find the examples?

**Comment by Adubbz** [comment]
They are in the examples folder in the repo. And pre-emptively: Replacing a biome only replaces it in your region, it doesn't replace it everywhere

**Comment by vaylor27** [comment]
Tank you! (:
