### ISSUE TITLE
terrablender crash

### ISSUE THREAD

**Issue by corpau** [Glitchfiend/TerraBlender#110]
### What's the issue you encountered?

try loading minecraft it tells me terrablender has crashed even updated the mod i noticed it was a couple behind and still crashes

### How can the issue be reproduced?

everytime i load my modded minecraft 

### Logs

https://gist.github.com/corpau/1a0f29a5c8ef84463f7fc571428f9844

### Mod Version

1.19.2-2.0.1.136

**Comment by Adubbz** [comment]
You need to delete your config files.
