### ISSUE TITLE
1.19.2 Fabric Server Keeps Crashing On Start 

### ISSUE THREAD

**Issue by danolhenl** [Glitchfiend/TerraBlender#116]
### What's the issue you encountered?

I've been trying to get this server but I keep running into issues. The latest one is a weird crash that doesn't seem to give any description; it just says "Minecraft has crashed!". Not sure if Terrablender is the mod that is causing the issue, but I figure I'll start here. I'm using Terralith, Oh The Biomes You'll Go, Corgilib, Terrablender, and Create. Thanks!

### How can the issue be reproduced?

Not sure how to recreate it, it's just been happening to me. So use the same OS and mods and version and mod loader as me I guess?

### Logs

https://gist.github.com/danolhenl/539c36313ac29aeb916823987ab3fa40#file-latest-log

### Mod Version

2.0.1.130

**Comment by Adubbz** [comment]
The crash you have provided is nothing to do with TerraBlender.

**Comment by danolhenl** [comment]
ok thank you!
