### ISSUE TITLE
1.19.2/1.19.4/1.20.1 Dedicated Server with Terrablender is causing world gen slowdown and thus MoveTooQuick errors In Minecraft Forge

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Glitchfiend/TerraBlender#118]
### What's the issue you encountered?

Please see my report
https://github.com/P3rf3ctXZer0/P3rf3ctXZer0s-Workshop/issues/3

### How can the issue be reproduced?

https://github.com/P3rf3ctXZer0/P3rf3ctXZer0s-Workshop/issues/3

### Logs

Multiple.

### Mod Version

TerraBlender-forge-1.19.2-2.0.1.136

### Additional information

https://github.com/P3rf3ctXZer0/P3rf3ctXZer0s-Workshop/issues/3

(I will be doing a deep dive test once 1.20.1 is considered forge stable.)

**Comment by JordanFromIT** [comment]
bump

**Comment by P3rf3ctXZer0** [comment]
I was able to actually test with flight thanks to iron jetpacks and reasonable view distance. I still consider waiting 30 seconds when traveling in a direction waiting for world to load to be an issue. Dev should figure out a better way to load world loading.

Ideally it would use a "load chunks around player first approach" but as of now this does not seem to be the case. What is happening is player is traveling the game does not catch up. I don't understand why terrablender does this but it is immersive breaking.

Please consider fixing dev.
