### ISSUE TITLE
TerraBlender crash on click at "Create a new world"

### ISSUE THREAD

**Issue by HonzaVinCZ** [Glitchfiend/TerraBlender#12]
### What's the issue you encountered?

Game crashes when I click "Create a new world"

### How can the issue be reproduced?

I do nothing else than described above. Launch game, click create a new world, game freezes for a small while a crashes.

### Logs

https://gist.github.com/HonzaVinCZ/f6670c161ff64ae84e7a79551bcca8fd

### Mod Version

1.1.0.54

### Additional information

Crash attemt 1:
[crash-2022-01-15_11.35.56-client.txt](https://github.com/Glitchfiend/TerraBlender/files/7874867/crash-2022-01-15_11.35.56-client.txt)

Crash attemt  2:
[crash-2022-01-15_12.02.39-client.txt](https://github.com/Glitchfiend/TerraBlender/files/7874868/crash-2022-01-15_12.02.39-client.txt)

Crash attemt  3:
[crash-2022-01-15_12.38.04-client.txt](https://github.com/Glitchfiend/TerraBlender/files/7874869/crash-2022-01-15_12.38.04-client.txt)

**Comment by Adubbz** [comment]
You need to update BOP.
