### ISSUE TITLE
Infinite bookshelves 1.19 .

### ISSUE THREAD

**Issue by Teresa369** [Glitchfiend/TerraBlender#120]
### What's the issue you encountered?

i started my minecraft world and used Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.7 with TerraBlender-forge-1.19-2.0.0.120 .

### How can the issue be reproduced?

 i crafted bookshelves, placed them and out of thin air, got more of the same amount after placing all of them. then they kept repeating that over and over again.

### Mod Version

1.19-2.0.0.120

**Comment by Adubbz** [comment]
This is almost certainly not a TerraBlender issue.
