### ISSUE TITLE
1.19.4 Critical injection failure

### ISSUE THREAD

**Issue by DAEXDO3240** [Glitchfiend/TerraBlender#121]
### What's the issue you encountered?

I added the TerraBlender API, starting the Run it stops me almost immediately and gives me an error regarding mixin.

### How can the issue be reproduced?

Implemented TerraBlender and BiomesOPlenty APIs.
-> Run ' MyMod [runClient] '
-> Task :runClient FAILED

### Logs

https://gist.github.com/DAEXDO3240/35b548426c955630a5a7934938adcb49

### Mod Version

1.19.4

**Comment by Adubbz** [comment]
Your build.gradle file needs to have mixins set up correctly otherwise this will happen. See the build.gradle file used by the examples.
