### ISSUE TITLE
This mod is a trojan horse, do NOT download it.

### ISSUE THREAD

**Issue by RichPrune** [Glitchfiend/TerraBlender#130]
### What's the issue you encountered?

So, terrablender is supposed to mix together all the modded biomes in with terralith biomes, cool. But then you actually play it. It is one of the most incompatible mods I have ever seen. So far, it has made it so the glimmering weald spawns on the surface when enabled, structures spawn horrible and worldgen sharp and squarey, and so many more. It doesn't even work with half the modded biomes I care about, like glowstone canyon. But thats not why I'm here today. 

           I'm here because it has the audacity to corrupt and crash worlds once you remove it, if it wasn't horrible enough. Removing terrablender makes the world crash on load,
the chunks r all permanently fucked up, and I have no backups. But the world isn't what I care about. I am making a public modpack that is already played by a lot of people, so now i face the dilemma: do i prevent my friends from updating their worlds to the biggest update yet, or do I not remove this trojan virus of a mod and let it continue wreaking havoc on all our worlds? It's been responsible for a LOT of headache. Thanks guys.

Please fix ur mod.

### How can the issue be reproduced?

Download my modpack.
Install terralith(it seems to work at first)
load a world and load chunks.
Uninstall terralith
Open world, crash.

### Logs

attached in additional info

### Mod Version

1.19.2

### Additional information

forge
[latest.log](https://github.com/Glitchfiend/TerraBlender/files/12667242/latest.log)

**Comment by RichPrune** [comment]
https://legacy.curseforge.com/minecraft/modpacks/mc-chocolate-edition this is my modpack btw.

**Comment by Adubbz** [comment]
Removing world generation mods such as Terralith after initially using them is expected to cause significant issues, and is not caused by TerraBlender. You should do your due diligence by creating a backup of your world before removing world generation mods. Your issue also is lacking in actual substance and just seems to be hyperbole and a misunderstanding of what a trojan horse is.
