### ISSUE TITLE
[1.20.1]  Grass doesn't generate under overhangs in the end using Nullscape

### ISSUE THREAD

**Issue by Reshy** [Glitchfiend/TerraBlender#133]
### What's the issue you encountered?

Mods that modify world generation to include more overhanging terrain cause grass and other similar blocks to not spawn on the undersides.

### How can the issue be reproduced?

Use Nullscape + a mod that adds biomes to the End like BYG/Better End/etc.

### Mod Version

TerraBlender-forge-1.20.1-3.0.0.169.jar

**Comment by Adubbz** [comment]
TerraBlender does not affect the end.
