### ISSUE TITLE
"Exception generating new chunks error"

### ISSUE THREAD

**Issue by CrypticVerse** [Glitchfiend/TerraBlender#137]
### What's the issue you encountered?

Developing a mod using TerraBlender, and when any world is started/opened, the log starts putting out "Exception generating new chunks", and the loading screen has visuals of loading chunks, but the percent at the top is stuck on 0%. When it is "done" loading chunks, the game crashes.

### How can the issue be reproduced?

Develop a mod using terrablender 3.0.0.169, and launch the game. Before today, 11/19/23, this worked without problems.

### Logs

https://gist.github.com/CrypticVerse/c63de1af535e1edf00deefc9670d84d6

### Mod Version

0.1.1-beta.1

**Comment by Adubbz** [comment]
Your log mentions a feature order cycle, which isn't a TerraBlender issue. Rather, it's standard Vanilla behaviour. You need to ensure your features are added in the same order as Vanilla's features to prevent this from happening.

**Comment by CrypticVerse** [comment]
Tried this and it worked. Thank you!
