### ISSUE TITLE
1.20.1 Crash for new version Fabric Loader 0.15.0(1)

### ISSUE THREAD

**Issue by DonorKrovi** [Glitchfiend/TerraBlender#142]
### What's the issue you encountered?

Look log

### How can the issue be reproduced?

Start server

### Logs

https://mclo.gs/iecYxkF

### Mod Version

TerraBlender-fabric-1.20.1-3.0.0.169

**Comment by Adubbz** [comment]
This is a problem with Region Unexplored's config system. Others have solved this by using Fabric Loader 0.14.25. You'll need to ask about it on their issue tracker/Discord.
