### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Nicolol1234** [Glitchfiend/TerraBlender#143]
### What's the issue you encountered?

Crash on starting the server

### How can the issue be reproduced?

No idea, just put some mods and start the server

### Logs

https://mclo.gs/jmuIinI

### Mod Version

1.20.2-3.2.0.14

**Comment by Adubbz** [comment]
This is not a TerraBlender issue. See https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/79

**Comment by KirboSoftware** [comment]
Please check v0.5.3.2 of regions unexplored fabric 👍 That should now have fixed this issue and my apologies Terrablender peeps for this
