### ISSUE TITLE
its not for 1.20.2 its for the latest update with 1.20.1

### ISSUE THREAD

**Issue by Thunderrock424242** [Glitchfiend/TerraBlender#146]
### What's the issue you encountered?

in meta data for the latest update the version was labled 3.0.0 but its supposed to be version 3.0..1.1

### How can the issue be reproduced?

use the latest terra blender with regions unexplored

### Mod Version

3.0.1.1

### Additional information

nope thats it

**Comment by Adubbz** [comment]
The corresponding builds have been removed and I would recommend using an older 1.20.1 build for the time being. @JT122406 will look into it when he has time.

**Comment by katubug** [comment]
Ope, I guess I should have checked here, first. Well, I can corroborate and I'll downgrade for now.

https://github.com/ochotonida/gardens-of-the-dead/issues/10

**Comment by Adubbz** [comment]
I fixed this myself, should be fine now
