### ISSUE TITLE
Failure message: TerraBlender (terrablender) has failed to load correctly

### ISSUE THREAD

**Issue by rythmfr** [Glitchfiend/TerraBlender#147]
### What's the issue you encountered?

Recently I tried to turn on my minecraft 1.20.1 forge server but it crashed, I tried restarting my pc and everything but it wouldn't fix it. The server was running fine beforehand I don't know why it is suddenly crashing. 

### How can the issue be reproduced?

Well, I don't know it just randomly occurred whilst I was trying to run the server, Maybe:

Start a new 1.20.1 Forge server.
Forge version 47.2.18
Add TerraBlender mod version 3.0.1.2 (1.20.1) to the servers "mods" folder
Launch Server.

I was expecting the server to run as usual but it actually just crashed.

### Logs

https://gist.github.com/rythmfr/7535b14f68002ab97db8384310b0dcb3

### Mod Version

1.20.1

### Additional information

If you require any more information please tell me.

**Comment by Adubbz** [comment]
You need to delete your config files
