### ISSUE TITLE
1.20.2 Forge TerraBlender has failed to load correctly

### ISSUE THREAD

**Issue by minustplust** [Glitchfiend/TerraBlender#148]
### What's the issue you encountered?

I was trying to enter Minecraft Forge 1.20.2 when all of a sudden it had an "error loading mods", with "TerraBlender (terrablender) has failed to load correctly. There's a text below saying "java.lang.ExceptionInInitializerError: null," 

### How can the issue be reproduced?

A few hours ago, I was playing Minecraft Forge 1.20.2 with the TerraBlender mod perfectly fine in multiplayer. I proceeded to log off and turn off my laptop. After I turned my laptop on again, I tried to enter Minecraft but was greeted with an error screen. I've deleted and redownloaded the mod for 2 times now, but the issue still persists. My Java Client (or whatever it's called) is on the latest version. I can't play in my multiplayer server without the TerraBlender mod. I'm currently using TLauncher if that helps.

### Logs

https://gist.github.com/minustplust/16083aa664aeec6c5c932e6d205884b6

### Mod Version

1.20-3.2.0.14

**Comment by Adubbz** [comment]
You need to delete your config files.

**Comment by minustplust** [comment]
Thank you Adubbz!
