### ISSUE TITLE
Latest Terrablender versions crashe with BCLib

### ISSUE THREAD

**Issue by LordOfTheWeebs** [Glitchfiend/TerraBlender#149]
### What's the issue you encountered?

When creating a new world with the latest versions of Terrablender(3.3.0.6-9) and BCLib(3.30.1) installed, with no other mods than the required Fabric API, the client crashes.

### How can the issue be reproduced?

Create a world of any type with any Terrablender version from 3.3.0.6 to 3.3.0.9 and BCLib version 3.30.1 installed.

### Logs

https://gist.github.com/LordOfTheWeebs/c2763304c60b3eced4d8f4eafb4206c3 (Added crash report if it helps)

### Mod Version

3.3.0.6 to 3.3.0.9

### Additional information

I apologize if this isn't the correct place to report such a crash/bug, but I thought I'd mention it since it likely began with Terrablender's recent addition of end biome alterations in TB.

**Comment by Adubbz** [comment]
Though this crash can probably be fixed, there’s a strong likelihood that end biomes added with TerraBlender won’t work, given they outright replace the end biome source with their own whilst we mixin to Vanilla’s
