### ISSUE TITLE
TerraBlender + Biomes O' Plenty crashing (Fabric/1.20.4)

### ISSUE THREAD

**Issue by mcm1903** [Glitchfiend/TerraBlender#150]
### What's the issue you encountered?

Right after hitting Play in the Minecraft Launcher the game crashes. 
It is a self-made Modpack via CurseFore, version 1.20.4

### How can the issue be reproduced?

The reason for the crash needs to be TerraBlender as disabling it in combination with Biomes O' Plenty lets the game start without any issue.

### Logs

---- Minecraft Crash Report ---- // Why did you do that?  Time: 2024-01-19 16:55:46 Description: Initializing game  java.lang.ExceptionInInitializerError 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) 	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:73) 	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:69) 	at net.minecraft.class_310.handler$chl000$supermartijn642corelib$beforeInit(class_310.java:13765) 	at net.minecraft.class_310.<init>(class_310.java:487) 	at net.minecraft.client.main.Main.main(Main.java:223) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.RuntimeException: Mixin transformation of terrablender.config.TerraBlenderConfig failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) 	at terrablender.core.TerraBlenderFabric.<clinit>(TerraBlenderFabric.java:27) 	... 13 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) 	... 18 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector create(Lterrablender/config/Config;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Number;Ljava/lang/Number;Ljava/lang/Number;)Ljava/lang/Number; in cristellib-common.mixins.json:MixinTerrablenderConfig from mod cristellib failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap cristellib-common-refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 21 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) 	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:73) 	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:69) 	at net.minecraft.class_310.handler$chl000$supermartijn642corelib$beforeInit(class_310.java:13765) 	at net.minecraft.class_310.<init>(class_310.java:487)  -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:Erweiterte Windows 32 Base-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		COMCTL32.dll:Bibliothek für Steuerelemente:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:Krypto-API32:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS-Client-API-DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:IP-Hilfs-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:Client-DLL für Windows NT-Basis-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:Client-DLL für Windows NT-Basis-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.23110.3 (9ebb3643d539a6fc4659898b1df3124d5da4c0a9):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		Ole32.dll:Microsoft OLE für Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		Pdh.dll:Windows Unterstützungs-DLL für Leistungsdaten:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:Remoteprozeduraufruf-Laufzeitumgebung:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:Allgemeine Windows-Shell-DLL:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation 		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		USER32.dll:Client-DLL für Windows USER-API (mehrere Benutzer):10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Windows HTTP-Dienste:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:MCI API-DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		bcrypt.dll:Bibliothek mit kryptografischen Primitiven von Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation 		combase.dll:Microsoft COM für Windows:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc.DLL:DHCP Clientdienst:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc6.DLL:DHCPv6-Client:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		fwpuclnt.dll:FWP/IPsec Benutzermodus-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		gdi32full.dll:GDI Client DLL:10.0.22621.2861 (WinBuild.160101.0800):Microsoft Corporation 		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jna4686373607651863114.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA) 		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft 		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation 		lwjgl.dll 		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		mswsock.dll:Microsoft Windows Sockets 2.0-Dienstanbieter:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		napinsp.dll:E-Mail-Namenshimanbieter:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		ncrypt.dll:Windows NCrypt-Router:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		ntdll.dll:DLL für NT-Layer:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		perfos.dll:DLL für Windows-Systemleistungsobjekte:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		pnrpnsp.dll:PNRP-Namespaceanbieter:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		profapi.dll:User Profile Basic API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		shlwapi.dll:Shell Light-weight-Hilfsprogrammbibliothek:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		win32u.dll:Win32u:10.0.22621.3007 (WinBuild.160101.0800):Microsoft Corporation 		windows.storage.dll:Microsoft WinRT Storage-API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		wintypes.dll:Windows-Basistypen-DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		ws2_32.DLL:Windows Socket 2.0-32-Bit-DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation 		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft Stacktrace: 	at net.minecraft.client.main.Main.main(Main.java:223) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- System Details -- Details: 	Minecraft Version: 1.20.4 	Minecraft Version ID: 1.20.4 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 233369256 bytes (222 MiB) / 444596224 bytes (424 MiB) up to 4294967296 bytes (4096 MiB) 	CPUs: 12 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz 	Identifier: Intel64 Family 6 Model 165 Stepping 2 	Microarchitecture: unknown 	Frequency (GHz): 2.59 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: Intel(R) UHD Graphics 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 1024.00 	Graphics card #0 deviceId: 0x9bc4 	Graphics card #0 versionInfo: DriverVersion=27.20.100.8729 	Graphics card #1 name: NVIDIA GeForce RTX 2060 with Max-Q Design 	Graphics card #1 vendor: NVIDIA (0x10de) 	Graphics card #1 VRAM (MB): 4095.00 	Graphics card #1 deviceId: 0x1f12 	Graphics card #1 versionInfo: DriverVersion=31.0.15.4633 	Memory slot #0 capacity (MB): 16384.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 16384.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 48078.16 	Virtual memory used (MB): 43180.36 	Swap memory total (MB): 15534.05 	Swap memory used (MB): 1219.15 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m 	Fabric Mods:  		anvilrestoration: Anvil Restoration 2.2 		appleskin: AppleSkin 2.5.1+mc1.20.3 		architectury: Architectury 11.0.11 		automaticdoors: Automatic Doors 4.6 		betterspawnercontrol: Better Spawner Control 4.4 		biomesoplenty: BiomesOPlenty 19.0.0.32 			com_electronwill_night-config_core: core 3.6.7 			com_electronwill_night-config_toml: toml 3.6.7 			net_jodah_typetools: typetools 0.6.3 		blur: Blur (Fabric) 3.2.0 			midnightlib: MidnightLib 1.5.3 			satin: Satin 1.15.0 		cardinal-components: Cardinal Components API 5.4.0 			cardinal-components-base: Cardinal Components API (base) 5.4.0 			cardinal-components-block: Cardinal Components API (blocks) 5.4.0 			cardinal-components-chunk: Cardinal Components API (chunks) 5.4.0 			cardinal-components-entity: Cardinal Components API (entities) 5.4.0 			cardinal-components-item: Cardinal Components API (items) 5.4.0 			cardinal-components-level: Cardinal Components API (world saves) 5.4.0 			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.4.0 			cardinal-components-world: Cardinal Components API (worlds) 5.4.0 		cloth-config: Cloth Config v13 13.0.121 			cloth-basic-math: cloth-basic-math 0.6.1 		clumps: Clumps 15.0.0.2 		collective: Collective 7.30 		continuity: Continuity 3.0.0-beta.4+1.20.2 		cristellib: Cristel Lib 1.2.0 			blue_endless_jankson: jankson 1.2.3 		darkloot: DarkLoot - Better Mob Loot 1.2.1 		detailab: Detail Armor Bar 2.6.3+1.20.4-fabric 		fabric-api: Fabric API 0.94.1+1.20.4 			fabric-api-base: Fabric API Base 0.4.36+78d798af4f 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.47+82b1bb3e4f 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f 			fabric-block-api-v1: Fabric Block API (v1) 1.0.15+78d798af4f 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f 			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f 			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f 			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f 			fabric-containers-v0: Fabric Containers (v0) 0.1.85+df3654b34f 			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.10+78d798af4f 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.21+78d798af4f 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.72+df3654b34f 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f 			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.21+78d798af4f 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.30+78d798af4f 			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.5+78d798af4f 			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.60+78d798af4f 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f 			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f 			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.6+bf1eca544f 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.9+06274a474f 			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f 			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.19+78d798af4f 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.17+78d798af4f 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.51+df3654b34f 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.33+78d798af4f 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.54+df3654b34f 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.13+78d798af4f 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.16+78d798af4f 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.54+78d798af4f 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f 			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.8+e84342304f 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f 		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2 		fabricloader: Fabric Loader 0.15.6 			mixinextras: MixinExtras 0.3.2 		forgeconfigapiport: Forge Config API Port 20.4.2 		fwaystones: Fabric Waystones 3.3.2+mc1.20.4 		glitchcore: GlitchCore 1.0.0.53 		hoetweaks: Hoe Tweaks 3.4 		indium: Indium 1.0.28+mc1.20.4 		inventoryprofilesnext: Inventory Profiles Next 1.10.9 		iris: Iris 1.6.14 			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1 		jade: Jade 13.2.1 		jamlib: JamLib 1.0.3+1.20.4 		java: OpenJDK 64-Bit Server VM 17 		jei: Just Enough Items 17.0.0.30 		libipn: libIPN 4.0.1 		mine-spawners: mine-spawners 1.0 		minecraft: Minecraft 1.20.4 		mineralchance: Mineral Chance 3.4 		nametagtweaks: Name Tag Tweaks 3.2 		owo: oωo 0.12.2+1.20.3 		rightclickharvest: Right Click Harvest 4.1.3+1.20.4 		shouldersurfing: Shoulder Surfing Reloaded 2.8.1 		shulkerboxtooltip: Shulker Box Tooltip 4.0.8+1.20.4 		skinlayers3d: 3d-Skin-Layers 1.6.2 		sodium: Sodium 0.5.5 		softerhaybales: Softer Hay Bales 3.2 		sound_physics_remastered: Sound Physics Remastered 1.20.4-1.3.1 		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16+a 		t_and_t: Towns and Towers 1.12.0 		terrablender: TerraBlender 3.3.0.10 		tramplestopper: Trample Stopper 6.0.1+mc1.20.4 		trashcans: Trash Cans 1.0.18 			team_reborn_energy: Energy 3.0.0 		travelersbackpack: Traveler's Backpack 1.20.4-9.4.0 		treeharvester: Tree Harvester 8.6 		trenzalore: Trenzalore 4.0.1 		villagernames: Villager Names 4.5.2 		xaerominimap: Xaero's Minimap 23.9.6 	Launched Version: fabric-loader-0.15.6-1.20.4 	Launcher name: minecraft-launcher 	Backend library: LWJGL version 3.3.2-snapshot 	Backend API: Unknown 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric' 	Universe: 404 	Type: Client (map_client.txt) 	Locale: en_US 	CPU: <unknown>

### Mod Version

3.3.0.10

### Additional information

The issue also happened with the modversion 
3.3.0.9
I wanted to delete the config file, but it was not even there.

**Comment by Adubbz** [comment]
This is an issue with Cristel Lib and needs to be resolved on their side. Please report this to them.
