### ISSUE TITLE
<void>

### ISSUE THREAD

**Issue by Catomax262** [Glitchfiend/TerraBlender#151]
<void>

**Comment by Adubbz** [comment]
No. If someone else wants to submit pull requests for 1.18 they are more than welcome to. I have no intention to continue support for it.

**Comment by Catomax262** [comment]
<void>

**Comment by Catomax262** [comment]
Still, do you know who even may help me with that?

**Comment by Adubbz** [comment]
Assuming your crash is what you submitted on another repo, that has nothing to do with TerraBlender to begin with. Feature order cycles are strictly to do with individual biome mods and the order they add their features.

**Comment by Catomax262** [comment]
<void>

**Comment by Catomax262** [comment]
Still, i wanted to contact you because neither Autumnity or Terra Incognita are being checked for issues.

**Comment by Catomax262** [comment]
The only mods i know that have interfered with biomes are Hal's EB and Biome makeover but even without these it crashes.

**Comment by Adubbz** [comment]
As I said before, feature order cycles are never anything to do with TerraBlender. We are involved in biome placement, not what features they contain. There's nothing for us to do here. You can only contact them about it.

**Comment by Catomax262** [comment]
<void>
