### ISSUE TITLE
Crash on startup in multiloader mod enviormenrt

### ISSUE THREAD

**Issue by CrypticVerse** [Glitchfiend/TerraBlender#154]
### What's the issue you encountered?

Crashing on startup using a multiloader environment, Fabric, Forge, and NeoForge.

### How can the issue be reproduced?

Create a multiloader project, create custom biome using TerraBlender, launch the game.

### Logs

https://gist.github.com/CrypticVerse/bae08fe332129d98beaf842d334f74e1

### Mod Version

3.3.0.10

**Comment by CrypticVerse** [comment]
[Fabric Crash Report](https://github.com/Glitchfiend/TerraBlender/files/14088875/crash-2024-01-29_14.44.22-client.txt)

**Comment by Adubbz** [comment]
You’re likely using TerraBlender before it has been initialized. Change the load order in mods.toml/use the onTerraBlenderInitialized entry point on Fabric

**Comment by CrypticVerse** [comment]
Going to try using the API fabric interface in loading process.

**Comment by CrypticVerse** [comment]
I made it so it initializes in Forge/Fabric, now its saying:

 Modules terrablender and TerraBlender.common export package terrablender.core to module cloth_config.
It will not even launch the game.

Fabric crashes upon trying to load a world with this message:
Missing key in ResourceKey[minecraft:root / minecraft:worldgen/biome]: ResourceKey[minecraft:worldgen/biome / betterbiomes:maple_forest].
I do have a maple_forest.json file to load the forest. It is in the correct directory.

Using Official Mappings.

**Comment by Adubbz** [comment]
The former would be either an incorrect Gradle setup or just how your dev environment is setup. See the examples on GitHub for they.

the ResourceKey thing is entirely Vanilla code and TerraBlender is not involved. TerraBlender does biome placement, not registration.
