### ISSUE TITLE
[Feature Request] Option to add End Biomes in 1.20.1

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/TerraBlender#157]
### Overview

**PS: Yes I'm aware that 1.20.1 isn't supported anymore, but since I saw something was added to 1.20.1, I wanted to try to suggest this as I really would love this feature to be implemented. 
If adding end biomes isn't possible in 1.20.1, or it isn't wanted, then I will also get that.
I know I can also update to 1.20.4, but some dependencies I also use for my mod aren't on 1.20.4 yet so I sadly cannot do that.**

So, basically, I would love it if it were possible to add end biomes w/ TB like BOP in 1.20.4. as every other method to add end biomes I found online didn't work (For example the main "The End" biome was replaced to so there were no pillars for the dragon boss fight for example). And I saw TB added the option for end biomes in 1.20.4, but since I can't update to 1.20.4 (as mentioned earlier in my PS note), I would really love it if this feature was added to 1.20.1.

### Why would this feature be useful?

As 1.20.1 is a more popular version as of right now (atleast I think that, maybe there are other reasons why newer versions are supported instead with TB for example, and I can understand that), more modders will have the option to add End Biomes to their mod using TerraBlender. Since TerraBlender helped me (and a lot of other modders), to add their own biomes to the overworld and nether, I would also like it if you can also add biomes to the End as well.

Like I said earlier, if this feature isn't able to be added to 1.20.1 because it isn't possible, not wanted or because of other reasons, I will understand that.

**Comment by Adubbz** [comment]
The recent changes to 1.20.1 were done via a pull request. My stance on these things is generally that I’m happy for others to submit pull requests backporting things as they see fit, though it’s not something I’ll be doing myself

**Comment by ghost** [comment]
Alright, that's understandable though!

**Comment by ghost** [comment]
Just saw it got added, so closing this :)
