### ISSUE TITLE
Crash on create world

### ISSUE THREAD

**Issue by AzureMonument** [Glitchfiend/TerraBlender#16]
### What's the issue you encountered?

The game crashed upon clicking 'create world' after going into single player. The crash log is below in the logs as a gist. I am playing with other mods as well.

### How can the issue be reproduced?

Launch mc, click single player, click new world. A lag spike will occur and after a bit 'saving world' text will appear briefly before the window completely closes due to the game crashing.

### Logs

https://gist.github.com/AzureMonument/dac0fbb54ebe2e2da4d2ed771b74ae43

### Mod Version

1.1.0.54

### Additional information

I tested with two other versions: The previous version of the mod I used, 1.1.0.39, does not have this crash. the latest beta 1.1.0.59, on the other hand, does still crash.
Forge version is 39.036

**Comment by Adubbz** [comment]
You need to update BOP.
