### ISSUE TITLE
Biomes spawning in ocean

### ISSUE THREAD

**Issue by robinroloff** [Glitchfiend/TerraBlender#160]
### What's the issue you encountered?

I created custom biomes using the terrablender library.
However, they spawn in the ocean and not where they are supposed to.
https://github.com/robinroloff/alpinemod this is my code

### How can the issue be reproduced?

Create a world, locate an ocean and then do /locate biome alpinemod:alps_valley
You will most likely find a biome in the ocean that is not supposed to be there

### Mod Version

3.2.0.14

**Comment by Adubbz** [comment]
As mentioned on Discord, this occurs when you have not included parameters for Vanilla biomes in your region (or your own substitutes for them). It is not a TerraBlender bug.
