### ISSUE TITLE
I'm trying to create a server

### ISSUE THREAD

**Issue by Fipex26** [Glitchfiend/TerraBlender#162]
### What's the issue you encountered?

I'm trying to create a server with this mod in version 1.21.1 and this mod crashed my server and I need it for other mods

### How can the issue be reproduced?

1. buy a server
2. put there mod Majnr - v2

### Logs

does not cause minecraft to crash

### Mod Version

3.0.1.4

**Comment by Adubbz** [comment]
No support can be provided for a crash unless you actually provide a crash log.

**Comment by Fipex26** [comment]
I see, seems like you are having the same issue as our previous chat. You have these options:
- Install terrablender and report the crash to terrablender's team
- Remove Regions Unexplored
- Update the modpack to 1.20.4 as the crash should happen there, and generate a new world
