### ISSUE TITLE
1.20.1 Fabric Mods Terrablender Crash

### ISSUE THREAD

**Issue by elitychu** [Glitchfiend/TerraBlender#163]
### What's the issue you encountered?

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terrablender'!"
![17144540203715805978844482999363](https://github.com/Glitchfiend/TerraBlender/assets/168510685/1532b04e-f965-418b-a132-946c3c197b68)
 

### How can the issue be reproduced?

Opening the game via the forge mod pack I created then pushing 'play' on the minecraft launcher creates the error. 

### Logs

<script src="https://gist.github.com/elitychu/e9cf972617c5645f593864a4ccfa166e.js"></script>

### Mod Version

1.20.1

### Additional information

We have played in this mod pack before with no issues; today is the first time it is giving trouble.

**Comment by Adubbz** [comment]
Your crash log suggests an issue with Simple Backpack, not TerraBlender.

**Comment by Adubbz** [comment]
You also say you're using Forge, but your crash log is from Fabric?

**Comment by elitychu** [comment]
Hello. The error does not mention the backpack mod. I don't know how that could be the issue.

We are using curseforge to create the modpack but all mods are Fabric API
![17144547721805252931461889565887](https://github.com/Glitchfiend/TerraBlender/assets/168510685/cdb6c2f4-4551-4d4a-9b5c-e99d7f239a74)

**Comment by Adubbz** [comment]
Please provide a correct crash report, what. You have linked is not a TerraBlender crash

**Comment by elitychu** [comment]
Hello. Sorry about that. This should be the correct log

<script src="https://gist.github.com/elitychu/fbe3f3ff474e57a92c443f3b2759e947.js"></script>

**Comment by Adubbz** [comment]
You need to delete your config files

**Comment by elitychu** [comment]
We tried that but it didn't work :(

**Comment by elitychu** [comment]
![17144560005518496085207403933382](https://github.com/Glitchfiend/TerraBlender/assets/168510685/b0f9b76d-2f3a-4a62-a3dd-53fef0e8147c)

**Comment by elitychu** [comment]
OK so we deleted the whole config folder then increased the memory allocation and it worked. Thank you for your time
