### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by etherealgears** [Glitchfiend/TerraBlender#165]
### What's the issue you encountered?

Game crashes on startup.

### How can the issue be reproduced?

Load game with Terrablender installed.

### Logs

https://gist.github.com/etherealgears/c98c7a0be81dd6701ffce1a5f38b38cf#file-gistfile1-txt

### Mod Version

TerraBlender Forge 1.20.1-3.0.1.5

### Additional information

I know Terrablender for MC versions below 1.20.2 ostensibly aren't supported, but since a new version for 1.20.1 was literally released today (as of filing this report) I'm assuming that doesn't apply since it's this brand new 1.20.1 version (1.20.1-3.0.1.5) which is crashing. Rolling back to 3.0.1.4 fixes the issue and the crash doesn't occur.

**Comment by Adubbz** [comment]
The new version released was as the result of a PR. Given this crash is happening I will revert those changes as I don't plan on working on 1.20.1 myself
