### ISSUE TITLE
Minecraft 1.19.2 Forge 43.4.0 crash at start

### ISSUE THREAD

**Issue by TheSexyYeti** [Glitchfiend/TerraBlender#170]
### What's the issue you encountered?

I keep getting a crash. The only mod I can find that I'm using that requires terrablender is project: vibrant journey. Otherwise I have no idea why it's causing the crash. At first I thought it was because I didn't have terrablender installed. But I still crash when I tried to load the game. Here's a pastebin link to the only crash log I got. https://pastebin.com/dRy7JQKz

### How can the issue be reproduced?

I honestly don't know. I have a bunch of mods I added to this modlist. And not sure what could be causing this.

### Logs

https://pastebin.com/dRy7JQKz

### Mod Version

2.0.1.166

**Comment by Adubbz** [comment]
You appear to have outdated dependencies. Either way, not a TerraBlender issue.
```
[00:16:21] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'domum_ornamentum', Requested by: 'minecolonies', Expected range: '[1.19-1.0.141-BETA,)', Actual version: '1.19-1.0.107-RELEASE'
	Mod ID: 'creativecore', Requested by: 'waterframes', Expected range: '[2.11.27,)', Actual version: '2.9.3'

```
