### ISSUE TITLE
Crash on opening F3 Menu

### ISSUE THREAD

**Issue by KyBeeS** [Glitchfiend/TerraBlender#183]
### What's the issue you encountered?

World froze for a second then instantly crashed 

### How can the issue be reproduced?

open f3 menu on dimension load after loading into world

### Logs

https://mclo.gs/ncJ6vr4

### Mod Version

4.1.0.3

### Additional information

Crash occurred in latest ATM10 release

**Comment by ghost** [comment]
I too have this issue, latest ATM10 release 0.52, Terrablender 4.1.0.3

Specifically when opening the F3 menu in the Undergarden dimension from said mod.

https://mclo.gs/8VQDhGo

**Comment by Satherov** [comment]
Same Crash here https://mclo.gs/MrPtr88

Step-by-Step to replicate here https://github.com/Glitchfiend/TerraBlender/issues/185

**Comment by junieclipse** [comment]
Also get this issue with the mod "Deeper And Darker" : https://mclo.gs/Eh3BPZy

**Comment by XXXS27** [comment]
Try Terrablender - 4.1.0.0

**Comment by thevortex** [comment]
is this not going to be addressed?

**Comment by cosmicvoices** [comment]
> Try Terrablender - 4.1.0.0

It helped thx
