### ISSUE TITLE
Crashes upon entering the End

### ISSUE THREAD

**Issue by shenyx110** [Glitchfiend/TerraBlender#185]
### What's the issue you encountered?

Crashes when setting up an end portal in creative mode and then entering the End

### How can the issue be reproduced?

Crashes when setting up an end portal in creative mode and then entering the End

### Logs

 Below

### Mod Version

4.1.0.3 neo

### Additional information

[minecraft-exported-logs-2024-09-27T20-04-58.log](https://github.com/user-attachments/files/17163984/minecraft-exported-logs-2024-09-27T20-04-58.log)
[crash-2024-09-27_20.04.48-client.txt](https://github.com/user-attachments/files/17163985/crash-2024-09-27_20.04.48-client.txt)
[minecraft-exported-crash-info-2024-09-27T20-05-02.zip](https://github.com/user-attachments/files/17163986/minecraft-exported-crash-info-2024-09-27T20-05-02.zip)

**Comment by shenyx110** [comment]
Seems to be an issue with [BiomesOPlenty](https://github.com/Glitchfiend/BiomesOPlenty) Logs [BiomesOPlenty](https://github.com/Glitchfiend/BiomesOPlenty) were also submitted.

**Comment by Satherov** [comment]
I managed the reliably reproduce this
- install [Oh the Biomes We've Gone to](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-weve-gone) and dependecies
- install [Nullscape](https://www.curseforge.com/minecraft/mc-mods/nullscape) and dependecies
- make a new world
- enter the end `/execute in minecraft:the_end run tp @s 0 90 0`
- go somewhere where chunks havn't generated yet `/tp @s 1000 ~ 1000`
- while they're generating, press F3
- Game will crash

It works fine with either mod installed alone, so I'm assuming it's some incompatibility between those two. 
I havent tested it with Biomes O Plenty yet, so maybe it's Nullscape messing with terrablender
