### ISSUE TITLE
Spawns vanilla biomes even if vanilla overworld region weight is set to 0

### ISSUE THREAD

**Issue by gaysarys** [Glitchfiend/TerraBlender#189]
### What's the issue you encountered?

I tried to disable vanilla biomes in favor of modded ones by setting overworld_region_weight value to 0 (also tried 1,-1), but vanilla biomes are still generated, I also tried to add a datapack that disables almost all vanilla biomes and even with it nothing changed (but it works correctly if Terralander is not installed).

### How can the issue be reproduced?

Install the newest version of NeoForge for 1.21.1
Add TerraBlender and any mods that uses it (BWG, RU, BOP)
Set vanilla_overworld_region_weight to 0 in the TB config

### Mod Version

4.1.0.5

### Additional information

tested on:
minecraft 1.21.1
neoforge 21.1.83
biomes mods: Regions Unexplored, Biomes we've gone

**Comment by racoonman2** [comment]
This sounds like the correct behavior. Most biome mods default to vanilla biomes when they don’t have an equivalent biome at a parameter point, so just disabling the vanilla region isn’t enough to fully get rid of them.

**Comment by Adubbz** [comment]
Yes, this is correct behaviour. Biomes mods typically fall back on Vanilla biomes when they don't have an equivalent. This is simply the reality of how biome placement works in recent Minecraft versions. SOMETHING has to substitute the removed biome. If you'd like for that substitute to be configurable, it'll have to be done on a mod-by-mod basis, it's not really a TerraBlender thing.
