### ISSUE TITLE
Crash when creating a world

### ISSUE THREAD

**Issue by IskallDoe** [Glitchfiend/TerraBlender#19]
### What's the issue you encountered?

Minecraft opens normally but when I click on single player to create a world it says that is Saving World and then crashes

### How can the issue be reproduced?

Mod version of TerraBlender 1.18.1-1.1.0.70
Forge Version 39.0.44

### Logs

https://gist.github.com/Imrald/a228afb23efce2bc86f1cf353cdd3e3d

### Mod Version

1.1.0.70

### Additional information

Crash report
https://gist.github.com/Imrald/bdce0374e9c345406daf62525a8de80b

**Comment by Adubbz** [comment]
That crash report indicates that TerraBlender hasn't actually been updated and you're still using version 1.18.1-1.1.0.54. Make sure you've updated the mod properly.

**Comment by IskallDoe** [comment]
I updated the mod but didn't delete the previous version.
I'm sorry for my dumbness and for the disturb.
I wish you a good day and thank you for the fast support

Il mer 19 gen 2022, 12:56 Adubbz ***@***.***> ha scritto:

**Comment by Sarund9** [comment]
Curse Forge installs the Latest release version, which is 1.1.0.54
If you go to the [Files Section](https://www.curseforge.com/minecraft/mc-mods/terrablender/files) you can see that the Main File is 1.1.0.54

Curse Forge will always download this Version, and will never download any other latest version unless it is marked as Release.

**Comment by IskallDoe** [comment]
In reality even from the Curse Forge app, if you click on the mod there is
even the Version Tab where you can update the mod. I clicked the latest
version, but in my mod folder there was still the non updated jar.
I will make sure to check better the next time, to avoid the same mistake.
Thank you for the support.
Have a great rest of the day

Il mer 19 gen 2022, 20:18 Sarund9 ***@***.***> ha scritto:

**Comment by brisingraerowing** [comment]
Yup, the CF app has a bug that causes it to not delete the previous version of a mod when installing a new one. I've been caught out by that one several times now.
