### ISSUE TITLE
[Crash] Concurrent Chunk Manage Engine (C2ME) Incompatability

### ISSUE THREAD

**Issue by greensad** [Glitchfiend/TerraBlender#20]
### What's the issue you encountered?

Game crashes on "Create New World" when both mods are installed. MC 1.18.1 + all mods are latest version, BYG/other biome/world gen mods are not installed.

### How can the issue be reproduced?

Launch the game -> 'Single Player' -> 'Create New World' = crash

### Logs

https://bytebin.lucko.me/WRGkFzRROc or https://crashy.net/tVP0jQC5EDhM7eXXLhfs

### Mod Version

1.1.0.70

### Additional information

**Multi-MC Instance:** https://drive.google.com/file/d/10Hs2OUmbJO_fmM3n8WDEF74FcEzUBGx-/view?usp=sharing
**Link to C2ME Issue:** https://github.com/RelativityMC/C2ME-fabric/issues/112

**Comment by Adubbz** [comment]
This has already been resolved on C2ME's side, you'll need to update it.
