### ISSUE TITLE
Datapack crash

### ISSUE THREAD

**Issue by TheButterbrotMan** [Glitchfiend/TerraBlender#21]
### What's the issue you encountered?

Crashes on world generation

### How can the issue be reproduced?

install https://www.curseforge.com/minecraft/modpacks/deathdusk

start with TerraBlender

### Logs

https://file.io/rhLG3yGmKwwO

### Mod Version

TerraBlender Fabric 1.18.1-1.1.0.70

**Comment by Adubbz** [comment]
This is a feature order cycle, which is a bug that occurs with mods that do not add their features in the correct order. This is not a TerraBlender thing, but rather a Vanilla one. This will need to be resolved in another mod, though the log doesn't make it clear which mod. Try removing mods that add world generation features or biomes until it works (TerraBlender itself adds neither).
