### ISSUE TITLE
no modded ores in modded biomes

### ISSUE THREAD

**Issue by Chuunkyz** [Glitchfiend/TerraBlender#25]
### What's the issue you encountered?

im using byg and magic fungi, two biome mods using terrablender
i just have the modded ores based on biome category (ae2 for example), the other ores like tech reborn and modern industrialisation are completely missing from the modded biomes...

### How can the issue be reproduced?

add terra blender, a mod using it and a mod with ores not based on biome category, like tech reborn

### Mod Version

latest

**Comment by Adubbz** [comment]
If this is only occurring in modded biomes then this isn't an issue with TerraBlender, it's either a problem with the mods adding the biomes or the mods adding the ores. If this was a TerraBlender bug the ores would also be absent in Vanilla biomes where they normally wouldn't.
