### ISSUE TITLE
[Forge] Using Terralith, BOP and BYG together doesn't generate all biomes

### ISSUE THREAD

**Issue by MarioAusItalien** [Glitchfiend/TerraBlender#28]
### What's the issue you encountered?

Using Terrablender with Terralith 2.0.12, Biomes O' Plenty 15.0.0.105 and Oh The Biomes You'll Go 1.3.5.7 together doesn't generate  any Terralith biomes. Vanilla, BOP and BYG biomes are generated. Forge version is 39.0.44

### How can the issue be reproduced?

Generate a world when having Terrablender, Terralith, BOP and BYG in your mods directory.

To check if the biomes were generated i closed the game after world generation, installed Natures Compass and restarted the game. For Natures compass i used a radius of  50000 with 500000 samples.

### Logs

https://gist.github.com/MarioAusItalien/9dddae1766d71ed49afa32a2e8e2d50c

### Mod Version

1.1.0.73

### Additional information

Using only two of the three biome mods works fine and generates all biomes included in these mods.

**Comment by drwoops** [comment]
it seems to work for me at this point in time.

**Comment by Whornag** [comment]
Similar issue here. Singleplayer 1.18.1 using only BYG the overworld and end biomes load without issue, but the nether defaults to vanilla. Tried setting "Replace default nether" to "false" as the in-game notification suggested but nothing changed.

**Comment by Adubbz** [comment]
Closing this as 1.18.1 is no longer supported. Please use 1.18.2.
