### ISSUE TITLE
BYG causes Amplified Nether to generate as vanilla nether

### ISSUE THREAD

**Issue by TheRobberPanda** [Glitchfiend/TerraBlender#29]
### What's the issue you encountered?

bug arises when terrablender is installed together with Amplified nether, terrablender somehow overrides amplified nether, then vanilla nether generates instead.

### How can the issue be reproduced?

1. install terrablender and amplified nether
2. go into the nether
3. nether generates as in vanilla, so amplified nether does not work

### Logs

https://gist.github.com/TheRobberPanda/873596556a89e140d726f04cd00a1f2f

### Mod Version

1.1.0.72

### Additional information

edited: "(fabric version)"

**Comment by TheRobberPanda** [comment]
This only happens in the fabric version for some unkown reason

**Comment by Adubbz** [comment]
With the Fabric version you'll need to press the "Data packs" then "Done" before creating the world. Forge seems to automatically load data packs whilst Fabric does not. Probably will need some kind of workaround

**Comment by Adubbz** [comment]
This should be fixed in 1.18.2.
