### ISSUE TITLE
[1.18.1] Fabric Crash on World Generation with Terrablender & Mod "Magical Forest"

### ISSUE THREAD

**Issue by pewblaze** [Glitchfiend/TerraBlender#30]
### What's the issue you encountered?

Wanted to create a new world, but it crashed. 

### How can the issue be reproduced?

Add Terrablender & Magical Forest (https://www.curseforge.com/minecraft/mc-mods/magical-forest) & Create a new World. Thats how it crashed for me.

### Logs

https://gist.github.com/pewblaze/ad28382e3e66db04a1132b7cbeeeac9a

### Mod Version

1.1.0.73

**Comment by Adubbz** [comment]
This would be due to  a bug with Terralith, not Magical Forest. This should be resolved now however.
