### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by xd4rkzghost01** [Glitchfiend/TerraBlender#31]
### What's the issue you encountered?

Crash the game upon startup. 1st mod i see on the "error" line in the crash log was TerraBlender.

Crash Log:
[crash-2022-01-29_03.25.27-client.txt](https://github.com/Glitchfiend/TerraBlender/files/7963303/crash-2022-01-29_03.25.27-client.txt)

Latest Log:
[latest.log](https://github.com/Glitchfiend/TerraBlender/files/7963302/latest.log)

### How can the issue be reproduced?

Open the game by the CurseForge manager/app and start it. Then Crash before getting trought the Mojang logo.

### Logs

https://gist.github.com/xd4rkzghost01/8998fa8861596950e23e0fa72c8f1380#file-lastest-log

### Mod Version

1.18.1 1.1.0.73

### Additional information

Lot of Mod include but Amplified Nether is disable due to issue #22 and/or #27

![CurseMod1181](https://user-images.githubusercontent.com/63568312/151654365-878c5761-9104-4749-bbd2-30467487d40e.png)

**Comment by Adubbz** [comment]
There's nothing in that crash that suggests this is an issue with TerraBlender.
