### ISSUE TITLE
TBMultiNoiseBiomeSource doesn't add multi-noise debug info

### ISSUE THREAD

**Issue by SmellyModder** [Glitchfiend/TerraBlender#32]
### What's the issue you encountered?

When using F3 to open the debug overlay, there is normally data displayed about multi-noise as seen in `MultiNoiseBiomeSource#addMultinoiseDebugInfo()`, but no data gets shown when using Terrablender.

### How can the issue be reproduced?

Simply open the debug overlay and notice the missing multi-noise information.

### Mod Version

1.18.1

**Comment by Adubbz** [comment]
This is fixed in 1.18.2 (we no longer replace MultiNoiseBiomeSource so Vanilla’s debug info is preserved)
