### ISSUE TITLE
[1.18.1] net.minecraft.ReportedException: Exception generating new chunk

### ISSUE THREAD

**Issue by Gbergz** [Glitchfiend/TerraBlender#34]
### What's the issue you encountered?

Walking around the nether mining minerals caused the server to crash.

### How can the issue be reproduced?

Not entirely sure how to reproduce the issue since I'm hosting a server with multiple people running around doing different things.
Crash is random and doesn't happen all the time. But the nether is where it is reproduced. (i think).

### Crash report

https://gist.github.com/Gbergz/63fa435bd8efb949c41a3977c31210f0

### Logs:
[2022-01-31-7.log](https://github.com/Glitchfiend/TerraBlender/files/7974369/2022-01-31-7.log)

### Mod Version

1.1.0.73

**Comment by Gbergz** [comment]
Here's another crash-log: https://gist.github.com/Gbergz/3b55d4b1b8fa39b32d986f2fa44d255b


EDIT, another one: https://gist.github.com/Gbergz/dcedf52d99526aefbc362df43025124c

**Comment by hacheraw** [comment]
Just in case it may help, I've uploaded a whole server directory with mods, world and crash logs.
You can replicate the error by just enthering the nether.

https://drive.google.com/file/d/1PPsvW6HEQfiPfqlClIIJLLlcJUNFBt5z (600mb)

I've tried to delete all player's uuid related info. I hope I managed to.

**Comment by Adubbz** [comment]
Closing this as it should be fixed in 1.18.2.
