### ISSUE TITLE
1.18.1 Server Crash

### ISSUE THREAD

**Issue by Tyrius1** [Glitchfiend/TerraBlender#36]
### What's the issue you encountered?

Flying in spectator and then again in creative on my server I encountered a crash when passing through the biomes o plenty wooded wasteland biome.

### How can the issue be reproduced?

After server restarted and i went back to the location of the event and it happened again.

### Logs

https://gist.github.com/Tyrius1/b3e8177503f7cb1c594396e2286a7e43 

### Mod Version

TerraBlender-forge-1.18.1-1.1.0.73

### Additional information

Server Crash:
https://pastebin.com/9cpuxneQ

**Comment by Adubbz** [comment]
This isn't actually a TerraBlender bug - This crash generally happens when something in the world causes stalling. Unsure if it's the cause here, but another player had this bug due to opening a chest from Dungeons Arise.
