### ISSUE TITLE
[FORGE] Json Dimensions added after TerraBlender is added are not loaded

### ISSUE THREAD

**Issue by Commoble** [Glitchfiend/TerraBlender#38]
### What's the issue you encountered?

JSON dimensions added to a world while the TerraBlender mod is installed on that world are not loaded and not teleportable-to. JSON dimensions present before TerraBlender is installed are not affected and still loaded. This seems to be a regression of #9 .

### How can the issue be reproduced?

* create and join new world (singleplayer)
* exit world (closing the integrated server)
* add datapack to world that adds a "fake_nether_a" dimension
* rejoin world
* fake_nether_a is visible in `/execute in` and teleportable-to
* close minecraft
* add terrablender
* restart minecraft and rejoin world
* fake_nether_a is still present
* exit world
* add "fake_nether_b" dimension to the datapack
* fake_nether_b is not visible in `/execute in` and not teleportable-to

### Logs

N/A

### Mod Version

1.1.0.73

### Additional information

This bug was reproduced on forge build 39.0.64, with no mods present other than TerraBlender

**Comment by Apothicon02** [comment]
This also happens to me on terrablender version 1.1.0.70

**Comment by recon88** [comment]
Same issue on the latest **Fabric** version of Terrablender but it seems like it's only affecting multiplayer there?! Couldn't reproduce it in singleplayer so far.

**Comment by TobiPeterG** [comment]
> Same issue on the latest **Fabric** version of Terrablender but it seems like it's only affecting multiplayer there?! Couldn't reproduce it in singleplayer so far.

I have this issue in the fabric version as well, using biomes you go and terralith
Can this be confirmed?

**Comment by Adubbz** [comment]
This should be fixed in 1.18.2.
