### ISSUE TITLE
Biome Indices have been registered, not  utilized

### ISSUE THREAD

**Issue by itsdinkd** [Glitchfiend/TerraBlender#39]
### What's the issue you encountered?

Encountering this bug on play where it crashes game

### How can the issue be reproduced?

Not sure

### Logs

https://paste.corebot.dev/luracopawu.sql

### Mod Version

1.0.73

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/D825UsUkmR

**Comment by TheButterbrotMan** [comment]
Maybe linked to #26

**Comment by Adubbz** [comment]
This was previously fixed though the build didn't get uploaded due to other issues, it should be addressed now.
