### ISSUE TITLE
Datapacks compatibility

### ISSUE THREAD

**Issue by MarkeR2005** [Glitchfiend/TerraBlender#4]
### Overview

Datapacks changing world height (such as jjthunder overhauled) is incompatible with terra blender, it just sets vanilla height values

### Why would this feature be useful?

This mod could be very useful for worldgen, but such a problem has the most influence in generation

**Comment by Monster-Zer0** [comment]
at least for noise generation.

**Comment by Sunconure11** [comment]
I second this. Biomes created via datapacks currently cannot be loaded if one has mods installed

**Comment by Adubbz** [comment]
This should be fixed in 1.18.2.
