### ISSUE TITLE
Terrablender appears to be preventing the creation of new worlds due to datapack issues

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/TerraBlender#41]
### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/5614902/154436512-6e77db1e-6ac0-44c8-9661-eb6d51f67732.png)

### How can the issue be reproduced?

1. Attempt to create a world
2. ???
3. Profit

### Logs

https://pastebin.com/WDRKQ0pK

### Mod Version

1.18.1-1.1.0.76

**Comment by Adubbz** [comment]
There’s nothing in your log that indicates this is a TerraBlender issue. Instead it appears one of the mods/data packs you have installed has a bad JSON file causing other json files to fail as well.
