### ISSUE TITLE
Crash on initializing a new world on a server

### ISSUE THREAD

**Issue by scribe-of-days** [Glitchfiend/TerraBlender#42]
### What's the issue you encountered?

Attempting to initialize a modded server for the first time results in a crash and TerraBlender is mentioned

### How can the issue be reproduced?

Please see the crash log paste provided

### Logs

https://mcpaste.io/0d995fd100a32863

### Mod Version

1.1.0.76

**Comment by Adubbz** [comment]
This is a feature order cycle which is an issue with one of the biome-adding mods you have installed rather than TerraBlender itself. You will have to use trial and error to figure out which one it is.
