### ISSUE TITLE
Weird biome placement

### ISSUE THREAD

**Issue by Matthysse** [Glitchfiend/TerraBlender#43]
### What's the issue you encountered?

There is a weird biome placement with the latest versions of forge, terrablender, and Biomes'O'Plenty. The only other biome mod I have is Biomemakeover. I don't know what informations I can add. Here are images of the problem:
An ocean biome on normal terrain:
![2022-02-18_12 24 38](https://user-images.githubusercontent.com/32510957/154698072-3fb0842d-a897-456d-a9da-052af61f9ab3.png)
A giant beach biome not near water:
![2022-02-18_12 26 09](https://user-images.githubusercontent.com/32510957/154698164-9f3a7946-55c2-4872-aa3b-a6aa1ab7a831.png)
An underground biome detectable on the surface:
![2022-02-18_12 36 30](https://user-images.githubusercontent.com/32510957/154698281-14253dba-9c01-4e9d-9970-a6614662552b.png)

### How can the issue be reproduced?

Loading a world with the mods I mentioned, it's immediately noticeable.

### Mod Version

1.1.0.77

**Comment by superninjakiwi** [comment]
I've noticed similar world issues when using BoP and Terralith. BoP or Terralith alone don't have this issue. One immediate way to reliably reproduce and recognize if worlds are not working properly is to teleport to an island biome, such as Rainbow Hills or Mushroom Fields. If the mod is alone, those biomes will be islands made entirely of that biome, surrounded by ocean. If the biome placement is messed up, you will often see those biomes as only a small part of a strange, extremely tall island made primarily of an ocean biome, which may contain multiple island biomes such as rainbow hills and mushroom fields in the center. Biome placement will also be very obviously along chunk boundaries, leading to an ugly, gridlike look.

**Comment by Jukabofy** [comment]
There is also a strange bug, that doesn't let nether mcreator biomes to generate surface blocks

**Comment by vaylor27** [comment]
Who uses mcreator anyways?

**Comment by superninjakiwi** [comment]
#109 is the new issue number for anyone else following this one.
