### ISSUE TITLE
Biome indices have been registered but haven't been utilised Crash on Start

### ISSUE THREAD

**Issue by SigynLaufeyson** [Glitchfiend/TerraBlender#45]
### What's the issue you encountered?

On single player, I cannot log into existing worlds or create new worlds.  Existing worlds indicate a datapack error, new worlds crash  with the following crash report:  [https://pastebin.com/vnjHa6yF](url).  This happens with version 1.1.0.77 back to 1.1.0.73.  This error I rolled back to 1.1.0.73 hoping it would work since I had been previously playing an existing world with it. 

With .77 installed the Game Crashed screen (upon attempting to create a new world) says:  _The game crashed whilst mouseclicked event handler Error: java.lang.RuntimeException:  Biomed indices have been registered but haven't been utilized: [12]. Either utilise the uniqueness assigned to your biome provider or set your provider's weight to 0.  Exit code: -1_

### How can the issue be reproduced?

The error log & crash report record my attempt to start an entirely new world.  I even rolled back to version 1.1.0.73 & the crash still happened.

### Logs

https://pastebin.com/PLfzZBf7

### Mod Version

1.18.1-1.1.0.77 down to 1.18.1-1.1.0.73

### Additional information

I run Biomes O Plenty, BYG, & Terralith.  All have been working just fine together until the .77 update.  I deleted all related config files for all the mods & the error still happens for both existing & new worlds.

**Comment by Adubbz** [comment]
You have a feature order cycle which is an issue between biome mods, not TerraBlender itself. This has repercussions that cause TerraBlender to crash,  however I wouldn’t consider that to be a TerraBlender bug. You’ve probably recently updated a biome mod of some sort which has introduced a feature order cycle and thus caused this to happen

**Comment by SigynLaufeyson** [comment]
Thank you for the prompt response!  It turned out to be Terralith.  I saw a mention of Terralith (different problem) & decided to see what would happen if it took it out.  Lo & behold I could create new worlds again.   I'm not sure it was working correctly so no loss there.  Thanks again!
