### ISSUE TITLE
[FABRIC]

### ISSUE THREAD

**Issue by imcasper** [Glitchfiend/TerraBlender#47]
### What's the issue you encountered?

Crash

### How can the issue be reproduced?

full mod set:
architectury-4.0.29.jar ( https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/ )
fabric-api-0.46.4+1.18.jar
fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
TerraBlender-fabric-1.18.1-1.1.0.77.jar

### Logs

https://gist.github.com/imcasper/04647d73ff8dfb929728b966aa514a09

### Mod Version

11077

**Comment by CyborgCabbage** [comment]
The version of architectury you are using is for 1.18.2, you should use this version [here](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3666162) as it is the latest version for 1.18.1

**Comment by imcasper** [comment]
Oh... Sorry.. You right. Now all work.

PS Do you plan to support 1.18.2?
