### ISSUE TITLE
[1.18.1 Crash]

### ISSUE THREAD

**Issue by itsdinkd** [Glitchfiend/TerraBlender#49]
### What's the issue you encountered?

Entering nether and generating a chunk crashes server / single player

### How can the issue be reproduced?

Enter Nether

### Logs

https://paste.corebot.dev/yixoqosodo.sql

### Mod Version

1.1.0.77

**Comment by Adubbz** [comment]
Closing this as it should be resolved in 1.18.2 (and the code involved in the crash no longer exists).
