### ISSUE TITLE
Startup crash with KubeJS and TerraBlender v1.1.0.45 [Forge]

### ISSUE THREAD

**Issue by sdarkwell** [Glitchfiend/TerraBlender#5]
### What's the issue you encountered?

Attempting to start Minecraft in GDLauncher with only the following mods installed results in a crash:

> **Error:** Signal Exits  **code:** 4294967295
> SLF4J: No SLF4J providers were found. SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.

### How can the issue be reproduced?

Start Minecraft with the following mods installed:

- Architectury (v3.4.9)
- KubeJS (v1801.1.4.1-build.271)
- Rhino (v1800.1.7-build.92)
- TerraBlender (v1.18.1-1.1.0.45)

### Logs

https://github.com/Glitchfiend/TerraBlender/files/7862990/latest.log

### Mod Version

1.1.0.45

### Additional information

This error only occurs with TerraBlender v1.1.0.45.
TerraBlender v1.1.0.44 starts without issue.

**Comment by Adubbz** [comment]
As per the log, you need to update Forge to at least 39.0.19. I required this version given they made important changes that improve performance when creating worlds.
