### ISSUE TITLE
Crash: Exception generating new chunk

### ISSUE THREAD

**Issue by CloWnicide** [Glitchfiend/TerraBlender#50]
### What's the issue you encountered?

Issue with generating new chunks, while exploring around the nether.

### How can the issue be reproduced?

Enter the nether, generate a few new chunks.

### Logs

https://gist.github.com/CloWnicide/a05b3a1302cb9cb985565918e1178902

### Mod Version

1.1.0.77

**Comment by Adubbz** [comment]
This should be fixed in 1.18.2.
