### ISSUE TITLE
Terrablend Crashes 1.18.2 java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists

### ISSUE THREAD

**Issue by FlashyCoderDude** [Glitchfiend/TerraBlender#54]
### What's the issue you encountered?

Server crashes with Latest FORGE Version

### How can the issue be reproduced?

Fabric 1.18.2
Fabric Loader 0.13.3

### Logs

https://gist.github.com/FlashyCoderDude/0f69b50f119d78f3f841ab1300641ca8

### Mod Version

1.1.0.91

**Comment by Adubbz** [comment]
This has already been fixed in .93. You need to update the mod.
