### ISSUE TITLE
[1.18.1] "bound must be positive" server crash

### ISSUE THREAD

**Issue by mosharky** [Glitchfiend/TerraBlender#56]
### What's the issue you encountered?

While flying around and generating my world in creative, my game crashed

### How can the issue be reproduced?

I do not know how to re-produce this, sorry

### Logs

[Crash](https://gist.github.com/mosharky/fb023d9d50cfac930b48baa2ea1c1bf9], [latest.log](https://gist.github.com/mosharky/d27e38ac2f34871e1e9db81e30d8eeaf)

### Mod Version

1.1.0.77

### Additional information

I'm not sure if this is caused by Terrablender itself or Biomes O' Plenty. BoP is the only mod in my pack that uses Terrablender.

**Comment by Adubbz** [comment]
Your log does not indicate this is an issue with TerraBlender or BOP. It’s a generic issue with mob spawning
