### ISSUE TITLE
Crash- on 1.18.2 actually

### ISSUE THREAD

**Issue by Lozf** [Glitchfiend/TerraBlender#58]
### What's the issue you encountered?

When initializing the game, it crashed.

### How can the issue be reproduced?

Simply trying to load the game.

### Logs

https://gist.github.com/Lozf/d1373d4e472877d3de791c3ec6e69753

### Mod Version

1.18.2-1.1.0.94

**Comment by Adubbz** [comment]
This is a BYG crash, not TerraBlender

**Comment by Lozf** [comment]
Ok, thanks!
