### ISSUE TITLE
Aether still buged

### ISSUE THREAD

**Issue by Niketats** [Glitchfiend/TerraBlender#59]
### What's the issue you encountered?

yeah, you already seen it on doscord, but Aether still generating overworld biomes

### How can the issue be reproduced?

Install TerraBlender and Paradise Lost
Enet Aether

### Logs

https://gist.github.com/Niketats/18a4caa9a1583591231c8b1906c8f64a

### Mod Version

fabric-1.18.2-1.1.0.98

**Comment by Adubbz** [comment]
This is an issue with Paradise Lost. They claim to be minecraft:overworld in their dimension's json file despite obviously not being the overworld. Other dimension mods do not do this. See: https://github.com/devs-immortal/Paradise-Lost/blob/b1.7/src/main/resources/data/the_aether/dimension/the_aether.json#L2=

**Comment by Jack-Papel** [comment]
Thanks for the tip. We've fixed the problem up on our end. The update's not out yet, but it will be released soon-ish.
