### ISSUE TITLE
Can't load world save in newest update of ATM7

### ISSUE THREAD

**Issue by DJSmoothMoney** [Glitchfiend/TerraBlender#6]
### What's the issue you encountered?

I am experiencing an error playing the latest ATM7 update (0.2.24). I am trying to load my world that I was last playing on the previous patch (0.2.23) and whilst loading I get an issue saying their is an error in currently selected datapacks. I shared my log files with the people on the ATM discord and one said that it appears to be an issue with TerraBlender. He quoted the following section.

> [13:01:55] [Render thread/ERROR]: Exception reading ...Instances\All the Mods 7 - ATM7 - 1.18.1 (1) (1)\saves\new atm7\level.dat_old
java.lang.IllegalArgumentException: Need at least one uniqueness value in parameter values.
    at terrablender.worldgen.TBClimate$UniquenessRTree.getUniquenessValues(TBClimate.java:192) ~[TerraBlender-forge-1.18.1-1.1.0.45.jar%23253!:1.18.1-1.1.0.45]

Can you confirm if this is an issue with TerraBlender and what may solve the issue
![image](https://user-images.githubusercontent.com/66222242/149388003-11c977d7-db47-4102-8a95-c041cff5e1cc.png)

### How can the issue be reproduced?

Loading a saveed from ATM7 0.2.23 in ATM7 0.2.24.

### Logs

[latest.log](https://github.com/Glitchfiend/TerraBlender/files/7865119/latest.log) ?

### Mod Version

1.1.0.41

**Comment by dauthiatull** [comment]
same issue as well heres my log
[latest.log](https://github.com/Glitchfiend/TerraBlender/files/7865212/latest.log)

**Comment by Thunder-Nova** [comment]
Are you in another dimension before the update? I got the same issue, but in one of the blue sky dimension.

@dauthiatull @DJSmoothMoney

**Comment by Thunder-Nova** [comment]
For some reason, I had to downgrade the mod to the previous version, and then reupgrade the mod to the version of the pack to make my world work. It happened twice for me. 

so went from version 1.1.0.41 (which is in ATM7 0.2.24)
back to 1.1.0.37 (which was my previous version of ATM7 0.2.23) load word, then back to 1.1.0.41 which worked... oddly

now updated to ATM7 0.2.25 which has 1.1.0.45 and it's happening again.

The biggest part of this issue is that when trying for safe mode, it doesn't even work.

**Comment by DJSmoothMoney** [comment]
> Are you in another dimension before the update? I got the same issue, but in one of the blue sky dimension.
> 
> @dauthiatull @DJSmoothMoney

I saved in the overworld and have only been to the nether.

**Comment by Adubbz** [comment]
I think there must be some other factor in play here. I've tried several of my old worlds created with TerraBlender versions as old as 1.1.0.21 and haven't managed to reproduce this. Are you all using dimension mods?

**Comment by Adubbz** [comment]
I just pushed a change that adds a fallback in the event that this occurs. A build should be up shortly.
