### ISSUE TITLE
1.18.1 Modded Server crash

### ISSUE THREAD

**Issue by Chococrispii** [Glitchfiend/TerraBlender#60]
### What's the issue you encountered?

Exploring in server when a sudden crash happened.

### How can the issue be reproduced?

Flying around and loading new chunks seems to trigger an event that causes a crash.

### Logs

https://gist.github.com/Chococrispii/76ec48f6d318ff67c71edc77522a9c34

### Mod Version

1.1.0.77.

### Additional information

https://pastebin.com/rM7xdLdq crash report. I don't believe terrablender is at fault but I would like to know what interaction with terrablender causes this result.

**Comment by Adubbz** [comment]
This appears mob-spawning related rather than TerraBlender related. In any case, we're only supporting 1.18.2 now, given the significant codebase differences to 1.18.1.
