### ISSUE TITLE
1.18.1

### ISSUE THREAD

**Issue by nokosi1736** [Glitchfiend/TerraBlender#61]
### What's the issue you encountered?

Teleporting into the nether would cause this cras
[crash-2022-04-14_06.08.12-server.txt](https://github.com/Glitchfiend/TerraBlender/files/8486750/crash-2022-04-14_06.08.12-server.txt)
h

### How can the issue be reproduced?

Teleporting into the nether via portal

### Logs

<script src="https://gist.github.com/nokosi1736/47a43d398ab8b108e3585afe7e219399.js"></script>

### Mod Version

1.1.0.77

**Comment by Adubbz** [comment]
1.18.1 is no longer supported. Please use 1.18.2.
