### ISSUE TITLE
Minecraft crashes every time i try and open it

### ISSUE THREAD

**Issue by lizneib** [Glitchfiend/TerraBlender#62]
### What's the issue you encountered?

i updated my Minecraft java to 18.2 and was getting mods for it ive always used biomes o plenty so i got that one first tired to open mc and it told me I needed to downlow terrablender so i did. whenever i tried to launch mc it immediately crashes. ive tried the fabric version and even tried putting just terrablender in the mods folder :(

### How can the issue be reproduced?

i honestly don't know what's happening with it. i just put it in the folder and it crashed my game

### Logs

https://gist.github.com/lizneib/33a3a3f539d17e879bbed46a9f0811c8

### Mod Version

1.18.2

**Comment by Adubbz** [comment]
This isn’t a TerraBlender issue. You seemingly have something wrong with your Forge config files. I would suggest deleting them
