### ISSUE TITLE
terrablender for 1.18.1 crashes when ever i try to enter a world

### ISSUE THREAD

**Issue by justawander** [Glitchfiend/TerraBlender#65]
### What's the issue you encountered?

when i tried to play on one of my worlds, the game crashed for me

### How can the issue be reproduced?

.

### Logs

https://bytebin.lucko.me/aXGjgNFeT5

### Mod Version

1.1.0.77

**Comment by Adubbz** [comment]
1.18.1 is no longer supported. Please use 1.18.2.
