### ISSUE TITLE
Issue with Bricks N' Blocks mod

### ISSUE THREAD

**Issue by CsillaAria** [Glitchfiend/TerraBlender#67]
### What's the issue you encountered?

when trying to use TerraBlender-forge-1.18.2-1.1.0.99 and BricksNBlocks2.3.3 at the same time no trees or plants appear anywhere. 

### How can the issue be reproduced?

Having  TerraBlender-forge-1.18.2-1.1.0.99 and BricksNBlocks2.3.3 in use at the same time.

### Mod Version

TerraBlender-forge-1.18.2-1.1.0.99

### Additional information

I have also notified the owner of Bricks N' Blocks of this issue.

**Comment by Adubbz** [comment]
This is an issue caused by MCreator, which is used by Bricks  N' Blocks. The developers of that will need to address this.

**Comment by Adubbz** [comment]
I've added a temporary workaround for this too
