### ISSUE TITLE
One of my friends keep crashing. Ik this says 1.18.2 but the discord says general questions instead of problems so not sure.

### ISSUE THREAD

**Issue by WaddleWaddle-sakura** [Glitchfiend/TerraBlender#69]
### What's the issue you encountered?

 My friend is getting a crash report everytime they use it, we're using it with oh the you'll go rebricated. But they are the only one who's had this issue as no one else has. We've tried upgrading versions downgrading same things with the fabric loader updating her minecraft. We've run out of options. I'm sorry if i was suppose to go into the discord but i felt cause it was a crash report and it said join the discord for general questions not very sure on where to go.      

### How can the issue be reproduced?

N/A

### Logs

---- Minecraft Crash Report ---- // You're mean.  Time: 5/9/22, 6:42 PM Description: Initializing game  java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terrablender'! 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:452) 	at net.minecraft.client.main.Main.main(Main.java:199) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.ExceptionInInitializerError 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) 	... 11 more Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available 	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) 	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) 	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) 	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) 	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) 	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) 	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) 	at terrablender.config.ConfigFile.<init>(ConfigFile.java:34) 	at terrablender.config.TerraBlenderConfig.<init>(TerraBlenderConfig.java:38) 	at terrablender.core.TerraBlenderFabric.<clinit>(TerraBlenderFabric.java:32) 	... 17 more   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) 	at net.minecraft.class_310.<init>(class_310.java:452)  -- Initialization -- Details: 	Modules:  		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.2203.5 (WinBuild.160101.0800):Microsoft Corporation 		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation 		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation 		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation 		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation

### Mod Version

1.18.1

**Comment by Adubbz** [comment]
1.18.1 is no longer supported. Please use 1.18.2.
