### ISSUE TITLE
TerraBlender is Crashing with Any Optimization Mods Installed

### ISSUE THREAD

**Issue by Coraline77447** [Glitchfiend/TerraBlender#7]
### What's the issue you encountered?

While I was making a new 1.18.1 modded world with Biomes O' Plenty along with TerraBlender, TerraBlender may be causing the game to crash while possibly having any optimization mods such as OptiFine installed.

Earlier today when I had nothing else to do while waiting for my favorite youtubers to upload today I was making and testing my latest 1.18.1 mods list that included BOP and TB (TerraBlender) along with Magnesium (a forge port of Sodium) and the game crashed the exact same way it did with OptiFine 3-4 hours later.
(OptiFine and Magnesium aren't compatible together btw)

Even tho Magnesium is currently for 1.18 (needs to be updated to 1.18.1 by the owner of Magnesium) the game crashed with Magnesium despite the versioning of Magnesium being for 1.18 but if it were to be updated to 1.18.1 I still would've experienced the game crashing with TerraBlender. 

### How can the issue be reproduced?

Install any forge optimization mod such as OptiFine, install TerraBlender (alongside with Biomes O' Plenty if need be) and try to get past mod loading to the title screen of Minecraft.

### Logs

https://gist.github.com/Coraline77447/fd3e8130ca71bab3801adad1b2ca4dbc

### Mod Version

1.1.0.50

### Additional information

Since TerraBlender is the dependency for Biomes O' Plenty, the issue may be coming from both mods but uncertain if Biomes O' Plenty is partially at fault. TerraBlender may be the only culprit to this issue.

Is TerraBlender compatible with any optimization mods btw? 
If not then could you try to add compatibility with at least Magnesium when it gets updated to 1.18.1? 
If you're unwilling to add compatibility with OptiFine which I'm completely fine with since it truly is a piece of garbage.
(Except for some of it's features it has, such as; dynamic lighting, zoom, FPS reader to show minimum and maximum framerates)

Btw I having second thoughts to some extent that what if this issue is coming from Biomes O' Plenty instead of TerraBlender? Since I took a look into the issue tracker for Biomes O' Plenty to see if anyone else is having the same issue as me and one issue report peaks my interest but it was created 16 days ago which at that time the versions of both mods are older than the latest versions (which I have the latest versions of both mods) and that report may be discussing a different issue than this report.

**Comment by Adubbz** [comment]
There's nothing going wrong with TerraBlender in your logs. Instead, it seems you probably need to update magnesium. From your log:
```
	Failure message: Mod magnesium requires minecraft 1.18
		Currently, minecraft is 1.18.1
```
