### ISSUE TITLE
Nether config

### ISSUE THREAD

**Issue by JonCaver** [Glitchfiend/TerraBlender#73]
### Overview

Would it be possible to add a config option to disable nether world generation with Terrablender and allow other mods to be used that currently do not mix well with mods that use terrablender?  

### Why would this feature be useful?

I am trying to use betternether with BYG. BYG uses terrablender as its resource for generating all dimensions. However there is currently a mod conflict with generation between the two mods where some of the biomes in the nether are barren using both together. If there was a way to turn off all nether generation but keep overworld generation on separately within terrablender this would fix the issue.

**Comment by Adubbz** [comment]
BYG does not use TerraBlender for its nether. It overrides the nether biome source with its own biome source. TerraBlender does not replace the nether biome source and is automatically replaced by any mods that choose to do so themselves. If such an issue exists it needs to be resolved on either BetterNether or BYG’s side.
