### ISSUE TITLE
1.18.2 Terrablender is corrupting rftoold dimensions

### ISSUE THREAD

**Issue by ixam22** [Glitchfiend/TerraBlender#75]
### What's the issue you encountered?

rftools stuff not spawning correctly, no structures

### How can the issue be reproduced?

a

### Mod Version

latest

**Comment by Adubbz** [comment]
We’re no longer supporting 1.18.2. If someone wishes to submit a PR backporting the fix for this they are welcome to do so.

**Comment by McJty** [comment]
1.18.2 is still a very active version. It's a bit unfortunate that you don't support this as this completely breaks my RFTools Dimension mod.

**Comment by daniele-bondi** [comment]
Is it possible to get a link to the commits that fixed the issue?
