### ISSUE TITLE
error installing crashes launch

### ISSUE THREAD

**Issue by antoniomh718** [Glitchfiend/TerraBlender#76]
### What's the issue you encountered?

every time I try to launch MC the game crashes stating that terrablender failed to install properly. I've tried to reinstall it change forge 1.19 versions etc and every time I crash. my friend seems to be able to play fine but not mine.

### How can the issue be reproduced?

I launch the game, either it doesn't load up at all or I get to a mc menu saying crash report.

### Logs

https://gist.github.com/antoniomh718/8c455ecb36c75c274c89d165313c48c0

### Mod Version

1.19-2.0.0.113

**Comment by Adubbz** [comment]
Your crash log states you do not have TerraBlender installed at all which is required by Biomes O' Plenty. This is an issue with your setup, not TerraBlender.

**Comment by antoniomh718** [comment]
> Your crash log states you do not have TerraBlender installed at all which is required by Biomes O' Plenty. This is an issue with your setup, not TerraBlender.

I understand it says that but the thing is that i have terrablender in the mod pack, its the same pack my friend is using and provided, and theirs works fine.
![Minecraft_ 1 19 6_29_2022 11_55_01 PM](https://user-images.githubusercontent.com/108324475/176589504-57a0d05c-e2eb-4d49-8436-b1c2b135c495.png)
![Screenshot (9)](https://user-images.githubusercontent.com/108324475/176589658-97bb2854-87d0-495a-9865-17b07eca2681.png)
