### ISSUE TITLE
Both Biomes O' Plenty and Oh The Biomes You'll Go Crash; says mod is missing when it isn't

### ISSUE THREAD

**Issue by JohnSmith00000000** [Glitchfiend/TerraBlender#78]
### What's the issue you encountered?

Launching the game with either Biomes O' Plenty and Oh The Biomes You'll Go Crash will cause a crash, and the log will say that TerraBlender is missing when it isn't. I suspect the reason is because the **game version is being included in the mod version, and is confusing the mod loader** (see logs).

### How can the issue be reproduced?

1) Install Forge
2) Install either **Biomes O' Plenty** or **Oh The Biomes You'll Go**
3) Install TerraBlender
4) Launch Minecraft
5) Game will crash

### Logs

[13:06:43] [Render thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase net.minecraftforge.fml.ModLoadingException: Mod §ebyg§r requires §6terrablender§r §o2.0.0.111 or above§r §7Currently, §6terrablender§r§7 is §o1.19-2.0.0.111

### Mod Version

2.0.0.111

### Additional information

Same problem with versions 2.0.0.112, and 2.0.0.113

**Comment by ZeGamingCuber** [comment]
same

**Comment by Adubbz** [comment]
The game version is now no longer included in the mod version

**Comment by JohnSmith00000000** [comment]
Thank you.
