### ISSUE TITLE
Terrablander will not load properly despite having all packs required

### ISSUE THREAD

**Issue by antoniomh718** [Glitchfiend/TerraBlender#79]
### What's the issue you encountered?

every time I load up Minecraft I get a crash error stating terrablander hasn't installed properly, which I'm aware its required for biomes o plenty, that being said the mod pack I have works for friends but not me and I'm unsure how to fix it.

### How can the issue be reproduced?

just launching the game brings me to the same page

### Logs

https://gist.github.com/antoniomh718/d421f6dfce5819e5180e4857aa338de9

### Mod Version

1.19-2.0.0.113

### Additional information

![176589504-57a0d05c-e2eb-4d49-8436-b1c2b135c495](https://user-images.githubusercontent.com/108324475/177020807-685b3bfd-cf39-4436-b8ce-7eabac6aad8d.png)
![176589658-97bb2854-87d0-495a-9865-17b07eca2681](https://user-images.githubusercontent.com/108324475/177020826-54312d1b-e275-4130-b5e6-ecd732eb8fa1.png)

**Comment by Adubbz** [comment]
It seems you've got bad config files. Try deleting them and try again

**Comment by antoniomh718** [comment]
> It seems you've got bad config files. Try deleting them and try again

I've cleared the folder a few times and and reinserted the mods and reinstalled forge etc, I've even tried installing terablender right from the source, is there anyway i can find out which mod isn't configuring properly or will I have to download every single one from its source individually?

**Comment by Adubbz** [comment]
You should just delete your entire config folder and let it regenerate. If that doesn't help you'll have to figure out what mod is breaking things through trial and error

**Comment by antoniomh718** [comment]
> You should just delete your entire config folder and let it regenerate. If that doesn't help you'll have to figure out what mod is breaking things through trial and error

how do I allow it to regenerate?

**Comment by Adubbz** [comment]
Just run the game after deleting it

**Comment by antoniomh718** [comment]
okay ill try that and if not ill do each mod one by one, after i find the mod causing the crashing what do i do from there? reinstall an uncorrupted one from the site rather than the pack folder?

**Comment by antoniomh718** [comment]
> Just run the game after deleting it

UPDATE: it would seem that with all the mods and just terrablander removed the game crashes before it loads, and if u remove biomes o plenty and leave terrablander in then i get the error shown before on the screenshot. the game loads without both these in the pack so it means its one of or both of these mods. how do i fix them?

**Comment by Adubbz** [comment]
Please do as I said and delete your config folder.

**Comment by antoniomh718** [comment]
> Please do as I said and delete your config folder.

ah sorry i misunderstood what u said earlier i didn't realize the config folder was its own entity vs the mod jars themselves, anyway IT LOADED. ill have to test it further and see if it works properly.

**Comment by antoniomh718** [comment]
> Please do as I said and delete your config folder.

it works, ty!
