### ISSUE TITLE
Crash when creating a new world

### ISSUE THREAD

**Issue by IskallDoe** [Glitchfiend/TerraBlender#8]
### What's the issue you encountered?

The game crashed while I was deleting a world to create another one and when I tried to create another world.

### How can the issue be reproduced?

Go to create a new world with included Biomes O'Plenty and TerraBlender plus Terralith 2.0 which it says to be compatible.

### Logs

https://gist.github.com/Imrald/f070621a2929573ec80d313a9764b7c8

### Mod Version

1.1.0.51

### Additional information

First log for the crash when deleting the world https://paste.ee/p/IIy4r
Second logfor the crash when creating a new world https://paste.ee/p/avUHF

**Comment by Adubbz** [comment]
According to your log you haven't actually updated TerraBlender, you're still using version 1.1.0.39. Make sure you've updated the mod properly.

**Comment by IskallDoe** [comment]
In Forge the mod appears as updated even if it's not the last version.
Checking I can see that it needs to be updated to version 1.1.0.53.
Thanks for the fast response!

Il ven 14 gen 2022, 13:12 Adubbz ***@***.***> ha scritto:
