### ISSUE TITLE
Crashes minecraft on startup

### ISSUE THREAD

**Issue by SpacedKey** [Glitchfiend/TerraBlender#80]
### What's the issue you encountered?

everytime i start the game with terrablender it gives the error message of: 
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'terrablender'!
Exit Code: -1"

i've tried updating to the latest version and it didn't fix the issue, nor any of the versions between newest and the version listed in the mod version section

### How can the issue be reproduced?

click play on minecraft launcher while on fabric profile with terrablender installed

### Logs

https://gist.github.com/SpacedKey/f83260683e1da36b5068bafff0071bd2

### Mod Version

2.0.0.118

### Additional information

i have this mod installed so i can play on a friend's server so not having it isn't really an option. nobody else using the same list of mods is having this problem

**Comment by Adubbz** [comment]
This is a BYG issue, not TerraBlender. Though you probably just need to delete your config files
