### ISSUE TITLE
For some reason, minecraft keeps crashing due to terrablender

### ISSUE THREAD

**Issue by OriOha707** [Glitchfiend/TerraBlender#81]
### What's the issue you encountered?

I was making a minecraft modpack and I wanted to try testing out the modpack
then it crashed because of terrablender and I don't know what to do
please help me

### How can the issue be reproduced?

I honestly don't know, I pasted the latest log, I hope that helps

### Logs

gist:5fee79dc078f11d96fb3d8257246cdc4

### Mod Version

1.1.0.102

**Comment by Adubbz** [comment]
See #79
