### ISSUE TITLE
Terrablender crash on Quilt 1.19

### ISSUE THREAD

**Issue by Sunconure11** [Glitchfiend/TerraBlender#83]
### What's the issue you encountered?

I'm trying to hunt down a specific crash, and it seems to be somewhat related to here. The issue appears to be mixin-related.

### How can the issue be reproduced?

If I knew everything about this, I would give such. I switched to 1.19 so I could begin rebuilding my pack in general.

### Logs

https://pastebin.com/sL5q2gMC

### Mod Version

1.19-2.0.0.119

### Additional information

Happens on Quilt.

Crash report: https://pastebin.com/JXiVdi2a

**Comment by Adubbz** [comment]
This is nothing to do with TerraBlender. ClientSpawnEntityMixin Is not from TerraBlender.
