### ISSUE TITLE
Examples are needed

### ISSUE THREAD

**Issue by MJRamon** [Glitchfiend/TerraBlender#84]
### Overview

Please provide code examples on how to use TerraBlender, not only how to install it. Some of us are learning Fabric, and it would help a lot. Thank you.

### Why would this feature be useful?

Learning purposes

**Comment by Adubbz** [comment]
These already exist and are linked to in the readme.

**Comment by MJRamon** [comment]
> These already exist and are linked to in the readme.

But in the example we replace vanilla biomes, at least in 1.18.1? What about adding new?

**Comment by Adubbz** [comment]
Biomes are replaced only in a mod’s specific region. They are not replaced everywhere
