### ISSUE TITLE
Incorrect list of possible biomes

### ISSUE THREAD

**Issue by MelanX** [Glitchfiend/TerraBlender#86]
### What's the issue you encountered?

The list of possible biomes isn't correct if looking at the list with orignal biomes.
I created a list for both:
https://gist.github.com/MelanX/31972acf6271a9b30a94cb0a12ab0ee7
As you can see, the `originalBiomeList` doesn't include any Ocean biome. In the `lazyPossibleBiomes`, you can find several Ocean biomes, in lines 65, 67, 69, 70, 71, 77, 84, 89, 107. 
These biomes shouldn't be included since they were removed by datapack and aren't even present in the `level.dat` file.

### How can the issue be reproduced?

Easiest way includes two additional mods, [Skyblock Builder](https://www.curseforge.com/minecraft/mc-mods/skyblock-builder) and [LibX](https://www.curseforge.com/minecraft/mc-mods/libx).
You can use this as config (just put in config folder): 
[common-config.zip](https://github.com/Glitchfiend/TerraBlender/files/9161235/common-config.zip)

This will automatically remove all ocean biomes. Even if reloading the same world (and because of this, using the `level.dat` as biome source source), the removed biomes do still exist in the lazyPossibleBiomes field.

### Mod Version

1.19-2.0.0.120

### Additional information

I wasn't sure if that's really the problem of TerraBlender or Biomes O' Plenty. Since both mods are from the same author (you), I thought I report it here because TerraBlender adds the Mixin for that.

Oh, and obviously when looking at the other required mods: Forge :)

Let me know if you need additional information.

**Comment by Adubbz** [comment]
This isn’t actually a bug. Datapacks are applied only to Vanilla regions. Mods (BOP included) can use whatever biomes they want in their regions without being affected by datapacks. This will almost always  include Vanilla’s ocean. If you want to take full responsibility for biome placement yourself through a datapack you should set the region weights to 0 in the config files of the respective mods (BOP in this case).
