### ISSUE TITLE
Crash Report for The Fabric Versions: 2.0.0.120 and 2.0.0.117

### ISSUE THREAD

**Issue by TheSourOnion** [Glitchfiend/TerraBlender#88]
### What's the issue you encountered?

I was downloading mods and it seems that I can't figure out how to fix this issue, unlike the other problems that popped up with downloading mods.

### How can the issue be reproduced?

Add the mods listed in the crash report with their specific versions. It has to do with one of the mods and compatibility maybe? I'm not too sure.

### Logs

https://gist.github.com/TheSourOnion/4f27c81e7fe829ffd4b11db6098230ae

### Mod Version

2.0.0.120, 2.0.0.117

### Additional information

I have only attempted these two versions of fabric. Also, I apologize if this report is sloppy, as I've never done a proper crash report before.

**Comment by Adubbz** [comment]
This is an issue with BYG’s config files, not TerraBlender

**Comment by TheSourOnion** [comment]
> This is an issue with BYG’s config files, not TerraBlender

Thank you for helping! Sorry for contacting the wrong person about this issue.
