### ISSUE TITLE
[Feature] Add project to modrinth.com

### ISSUE THREAD

**Issue by Sammcb** [Glitchfiend/TerraBlender#98]
### What is the new feature or improvement?

Hi, would it be possible for you to add this mod to [modrinth](https://www.modrinth.com)?

Modrinth is an open source alternative to CurseForge and offers a great API for users to interact with mods and modpacks. I am building a script to help manage modpacks that uses the modrinth API. I really like this mod and would love to see it on Modrinth so I can add it to the modpack I am creating!

Thanks so much!

### Why would this feature be useful?

Personally, I would find it really useful to have the option to download this mod from Modrinth so I can use it with my modpack manager. Thanks!

**Comment by Adubbz** [comment]
TerraBlender has been added to Modrinth.
